name: Deploy to GitHub pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate Files
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd ./public
        git init
        git add -A
        git config --local user.email "jaab30@yahoo.com"
        git config --local user.name "Jorge Alvarez"
        git commit -m 'deploy'

    - name: work around permission issue
      run: git config --global --add safe.directory /github/workspace/public

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./public